# Generated by Django 5.1.1 on 2024-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='Single', max_length=50),
        ),
    ]
